steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-south1-docker.pkg.dev/vishakha-403211/test-tf/test-tf"
      - "--build-arg"
      - "GIT_COMMIT=$(cat ./git_commit_sha.txt)"
      - "-f"
      - "Dockerfile"
      - "."

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-south1-docker.pkg.dev/vishakha-403211/test-tf/test-tf"

    - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/flask-app'
    - 'flask-app=gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

substitutions:
  _COMPUTE_ZONE: asia-south1  # Replace with your cluster's zone
  _CLUSTER_NAME: autopilot-cluster-1-test  # Replace with your cluster name

# Options configuration at the root level
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: "projects/vishakha-403211/locations/asia-south1/workerPools/test-tf"
