steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/test-tf/flask-app:$COMMIT_SHA', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/test-tf/flask-app:$COMMIT_SHA']

  # Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    env:
      - 'TF_VAR_project_id=$PROJECT_ID'

  # Run Terraform plan
  - name: 'hashicorp/terraform:latest'
    args: [
      'plan',
      '-var', 'project_id=$PROJECT_ID',
      '-var', 'region=asia-south1'
    ]

  # Apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: [
      'apply',
      '-auto-approve',
      '-var', 'project_id=$PROJECT_ID',
      '-var', 'region=asia-south1'
    ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/test-tf/flask-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
