steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/app:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/app:$COMMIT_SHA']

  # Run Terraform init
  - name: 'hashicorp/terraform:latest'
    args: ['init']

  # Run Terraform plan
  - name: 'hashicorp/terraform:latest'
    args: [
      'plan',
      '-var', 'project_id=$PROJECT_ID',
      '-var', 'region=${_REGION}',
      '-var', 'image_tag=$COMMIT_SHA'
    ]

  # Run Terraform apply
  - name: 'hashicorp/terraform:latest'
    args: [
      'apply',
      '-auto-approve',
      '-var', 'project_id=$PROJECT_ID',
      '-var', 'region=${_REGION}',
      '-var', 'image_tag=$COMMIT_SHA'
    ]

substitutions:
  _REGION: us-central1
  _REPOSITORY: app-repository
